<?php
namespace syriashop\lib;

class Languages {
    
    public static function lang( $words, $lang = "ar" ) {
        $ar = array(
            // global
            "report" => "ابلاغ",
            "unsave" => "الغاء الحفظ",
            "AnUnexpectedErrorOccurred" => "حدث حطأ غير متوقع",
            "dirTips" => "right",
            "btnAddAds" => "اضافة اعلان",
            "add" => "اضافة",
            "cancel" => "الغاء",
            "dashboard" => "لوحة التحكم",
            "learnMore" => "عرض المزيد",
            "allCountry" => "جميع البلدان",
            "allCity" => "جميع المحافظات",
            
            // Nav
            "signUp" => "تسجيل",
            "signIn" => "دخول",
            "signInFace" => "الدخول بحساب فيسبوك",
            "more" => "المزيد",
            "country" => "البلد",
            "city" => "المحافظات",
            "profile" => "الملف الشخصي",
            "chooseLang" => "اختر اللغة",
            "titleGetAds1" => "الإعلانات",
            "item1GetAds1" => "اعلانات البيع",
            "item2GetAds1" => "اعلانات الشراء",
            "item3GetAds1" => "اعلانات الإيجار",
            "item4GetAds1" => "جميع الإعلانات",
            "categoriesNav" => "الفئات",
            "signOut" => "تسجيل الخروج",
            "inputSearch" => "بحث...",
            
            // Client Default
            "maxViews" => "الأعلى مشاهدة",
            "newsAds" => "أحدث الإعلانات",
            "notFoundAds" => "لايوجد اعلانات حالياً",
            "readMore" => "قراءة المزيد",
            "next" => "التالي",
            "prev" => "السابق",
            "today" => "اليوم",
            "yesterday" => "امس",
            "twodays" => "منذ يومين",
            "titleNotFoundAds" => "نعتذر! لايوجد اعلانات في هذا القسم",
            "textNotFoundAds" => "اعد المحاولة في وقت لاحق",
            "successAddFavorite" => "تم اضافة الاعلان الى المفضلة",
            "errorAddFavorite" => "فشل اضافة الاعلان الى المفضلة",
            "successRemoveFavorite" => "تم ازالة الاعلان من المفضلة",
            "errorRemoveFavorite" => "فشل ازالة الاعلان من المفضلة",
            "messageClientBlockUser" => "تم حظرك من النشر من قبل الآدمن",
            "titleContainerCountry" => "اختر البلد المراد اظهار اعلاناتها",
            "titleContainerCity" => "اختر المحافظة المراد اظهار اعلاناتها",
            "showLastAds" => "عرض أحدث الإعلانات",
            
            // SignIn & SignUp
            "email" => "البريد الالكتروني",
            "password" => "كلمة المرور",
            "remberMe" => "تذكرني",
            "forgetPassword" => "هل نسيت كلمة المرور",
            "codeCheck" => "ادخل مجموع الرقمين التاليين",
            "dontHaveAccount" => "ليس لديك حساب",
            "clickHere" => "اضغط هنا",
            "username" => "اسم المستخدم",
            "haveAccount" => "هل لديك حساب",
            "notEmptyEmail" => "قم بملئ حقل البريد الالكتروني",
            "EmailIsExists" => "البريد الالكتروني الذي ادخلته موجود مسبقاً",
            "notEmptyUserName" => "قم بملئ حقل الاسم",
            "countUserName" => "عدد احرف الاسم يجب ان يكون اكبر من 4 احرف و اصغر من 40 حرف",
            "checkValidEmail" => "تأكد من صحة البريد الالكتروني",
            "notEmptyPassword" => "قم بملئ حقل الباسورد",
            "countPassword" => "عدد احرف كلمة المرور يجب ان تكون اكبر من 5 احرف واصغر من 40 حرف",
            "passwordIncorrect" => "كلمة المرور غير صحيحة",
            
            // Confirm Email
            "confirmTitle" => "تأكيد البريد الاكتروني",
            "bodyMessageConfirm" => "لقد قمت بانشاء حساب على موقع Syria Shop, اكتب كود التحقق التالي الذي طُلب منك في مربع التحقق",
            "wellcomeConfirm" => "مرحباً",
            "footerConfirm" => "مع خالص التمنيات, <a href='https://www.facebook.com/qusayshartah'>مطور</a> موقع Syria Shop",
            "EnterCode" => "ادخل الكود",
            "sendCode" => "تأكيد",
            "noteConfirm" => "ادخل الكود الذي تم ارساله الى الايميل الخاص بك",
            "notEmptyCode" => "قم بملئ حقل الكود",
            "errorConfirmEmail" => "الكود الذي ادخلته غير صحيح",
            "messageSuccessResendCode" => "تم اعادة ارسال الكود",
            "messageErrorResendCode" => "فشل ارسال الكود",
            "resendCode" => "في حال لم تتلقى الكود <a id='sendCode'>اضغط هنا</a> لاعادة ارساله مرة اخرى.",
            
            // reset Password
            "titleResetPassword" => "اعادة تعيين كلمة المرور",
            "noteAfterSendMail" => "تم ارسال  رمز التحقق الى ايميلك قم بالتحقق منه في قسم البريد الالكتروني او قسم الرسائل الغير مرغوب فيها.",
            "checkEmail" => "تحقق من الايميل",
            "EmailIsNotExists" => "البريد الالكتروني الذي ادخلته غير موجود",
            "bodyMail" => " لقد قمت بتقديم طلب لإعادة تعيين كلمة المرور الخاصة بك على موقع Syria Shop قم بكتابة هذا الكود لتتمكن من اعادة تعيين كلمة المرور",
            "save" => "حفظ",
            "enterNewPasswprd" => "ادخل كلمة المرور الجديدة",
            
            // newAds Default
            "chooseCat" => "اختر احد الفئات",
            
            // newAds addAds
            "infoAds" => "معلومات المنتج",
            "catName" => "سيتم حفظ الاعلان في القسم: ",
            "inputTitleAds" => "عنوان الاعلان",
            "inputDescAds"  => "وصف الاعلان",
            "inputTypeAds"  => "نوع الإعلان",
            "phoneuser" => "رقم الهاتف",
            "countryNumber" => "مفتاح البلد",
            "countryother" => "غير ذلك",
            "Examplephoneuser" => "مثال: 956343074",
            "ExampleTags" => "هنا تكتب الكلمات المفتاحية التي تدل على اعلانك كي يظهر في نتائج البحث",
            "whatsapp" => "واتساب  ",
            "ads" => "إعلان شراء",
            "sellAproduct" => "إعلان بيع",
            "rentAproduct" => "إعلان إيجار",
            "priceAds" => "سعر المنتج بالليرة السورية",
            "locationAds" => "مكان وجود المنتج",
            "discountAds" => "هل المنتج قابل للتفاوض",
            "tags" => "مثال: mobile+samsung+samsung s7",
            "expireAds" => "تاريخ انتهاء الإعلان",
            "sendAds" => "نشر",
            "Adsformat" => "شكل المنتج",
            "negotiable" => "قابل للتفاوض",
            "locationads2" => "وجود المنتج",
            "messageEmptyItemName" => "قم بملئ حقل عنوان الاعلان",
            "messageGTItemName" => "عدد احرف عنوان الاعلان يجب ان يكون اكبر من 3 احرف واصغر من 50 حرف",
            "messageEmptyItemDesc" => "قم بملئ حقل وصف الاعلان",
            "messageEmptyItemPrice" => "قم بملئ حقل سعر المنتج",
            "messageEmptyItemLocation" => "قم باختيار مكان وجود المنتج",
            "messageEmptyItemType" => "قم باختيار نوع الاعلان",
            "messageEmptyPhoneUser" => "قم بادخال رقم هاتفك",
            "messageEmptyWhatsapp" => "قم بادخال رقم الوتساب",
            "messageCountFile" => "اقصى عدد للملفات هو 7",
            "messageAllowFile" => "الملفات المسموحة هي png - jpg - jpeg - gif - mp4",
            "messageAllowFileImgOnly" => "الملفات المسموحة هي png - jpg - jpeg - gif",
            "messageSizeFileImg" => "حجم الصورة يجب ان لا يتعدى ال 10 ميغا",
            "messageSizeFileVideo" => "حجم الفيديو يجب ان لا يتعدى ال 40 ميغا",
            "messageLoadingTitle" => "جار النشر...",
            "messageLoadingNote" => "الآن تمت إضافة المنتج ، يرجى الانتظار حتى انتهاء التنزيل.",
            "titleMessageAlarm" => "اضافة منتج جديد",
            "messageAlarm1" => "تم اضافة عنصر جديد في القسم ",
            "messageAlarm2" => "قم بزيارة الموقع لمشاهدته",
            "messageAlarm3" => "رابط الموقع: http://syria-shop.com",
            "messageEmptyTags" => "قم بكتابة كلمة واحدة على الاقل في حقل الكلمات المفتاحية",
            "messageSuccessAddAds" => "تمت اضافة المنتج بنجاح",
            "messageDeleteAddAds" => "تمت حذف المنتج بنجاح",
            "messageErrorAddAds" => "حدث خطأ ما",
            
            // edit Ads
            "productAttachments" => "مرفقات الاعلان",
            "deleteImg" => "حذف المرفق",
            "deletedAttachment" => "تم حذف المرفق بنجاح",
            "errorDeletedAttachments" => "فشل حذف المرفق",
            "notFoundAttachments" => "المرفق غير موجود او تم حذفه",
            "messageCountFileEdit" => "عدد المرفقات المسموح بها ككل هو 7",
            "categorieName"  => "القسم",
            
            // categories
            "enableAlarm" => "تم تفعيل التنبيهات لهذا القسم",
            "disableAlarm" => "تم الغاء تفعيل التنبيهات لهذا القسم",
            "enableDisabledAlarm" => "تفعيل / الغاء تفعيل التنبيهات",
            
            // Show Ads
            "showAdsCategorie" => "القسم",
            "showAdsCountry" => "البلد",
            "showAdsLocation" => "المحافظة",
            "showAdsPrice" => "السعر",
            "showAdsRent" => "للإيجار",
            "showAdsPhone" => "الهاتف",
            "showAdsWhatsapp" => "واتساب",
            "showAdsViews" => "عدد المشاهدات",
            "showAdsDiscoint" => "قابل للتفاوض",
            "showAdsYes" => "نعم",
            "showAdsNo" => "لا",
            "after" => "بعد",
            "1day" => "يوم",
            "2day" => "يومين",
            "3day" => "3 ايام",
            "4day" => "4 ايام",
            "5day" => "5 ايام",
            "6day" => "6 ايام",
            "7day" => "7 ايام",
            "showAdsTags" => "الكلمات المفتاحية",
            "adsOthersTitle" => "اعلانات ذات صلة",
            "notFoundadsOthers" => "لايوجد اعلانات ذات صلة بهذا الاعلان",
            
            // search
            "resultSearch" => "نتائج البحث عن ",
            
            // Profile
            "myAds" => "اعلاناتي",
            "myInfo" => "معلوماتي",
            "favorite" => "المفضلة",
            "messageSuccessSaveData" => "تم حفظ البيانات",
            "messageLoadingTitleLogo" => "جار الحفظ...",
            "messageLoadingNoteLogo" => "جار تحديث الصورة الشخصية, يرجى الانتظار.",
            "messageSuccessEditMyImg" => "تم تغيير الصورة الشخصية",
            "can'tChangeEmail" => "لا يمكنك تغيير بريدك الالكتروني",
            
            // Dashboard
            //// default
            "dashboardControlPanel" => "لوحة التحكم",
            "dashboardClients" => "المستخدمين",
            "dashboardAds" => "الاعلانات",
            "dashboardCategories" => "الفئات",
            "dashboardCountry" => "البلدان",
            "dashboardCity" => "المدن",
            "dashboardReports" => "الابلاغات",
            "dashboardLastUsers" => "آخر 5 مستخدمين",
            "dashboardLastAds" => "آخر 5 اعلانات",
            "dashboardNotFoundAds" => "لايوجد اعلانات حاليا",
            "dashboardNotFoundUser" => "لايوجد مستخدمين حاليا",
            "dashboardTitleStatistcItems" => "احصائيات الاعلانات",
            "dashboardTitleStatistcUsers" => "احصائيات المستخدمين",
            
            //// Users
            "dashboardTypeUser" => "صلاحية المستخدم",
            "dashboardControl" => "التحكم",
            "dashboardBlock" => "حظر/فك الحظر",
            "dashboardMessageDeleteUser" => "تم حذف المستخدم بنجاح",
            "dashboardMessageBlock" => "تم حظر المستخدم بنجاح",
            "dashboardMessageUnBlock" => "تم فك حظر المستخدم بنجاح",
            "dashboardMessagePermissions" => "تم اعطاء اذن المدير بنجاح",
            "dashboardMessageUnPermissions" => "تم الغاء اذن المدير بنجاح",
            //// Items
            "dashboardPublisher" => "الناشر",
            "dashboardItemsCountry" => "البلد",
            "dashboardItemsCity" => "المدينة",
            "dashboardViewItem" => "مشاهدة الاعلان",
            "dashboardDateAdded" => "تاريخ الاضافة",
            
            //// Country
            "dashboardAddCountry" => "اضافة بلد",
            "dashboardEditCountry" => "تعديل بلد",
            "dashboardColumnLocationName" => "اسم البلد",
            "dashboardColumnLocationKey" => "مفتاح البلد",
            "dashboardColumnLocationIcon" => "راية البلد",
            "dashboardColumnLocationCity" => "المحافظات",
            "dashboardMessageDeleteCountry" => "تم حذف البلد بنجاح",
            "dashboardNotFoundCountry" => "لايوجد بلدان حاليا",
            "dashboardMessageAddCountry" => "تم اضافة البلد بنجاح",
            "dashboardMessageEditCountry" => "تم تعديل البلد بنجاح",
            "dashboardMessageEnterCountryName" => "ادخل اسم البلد",
            "dashboardMessageEnterCountryKey" => "ادخل مفتاح البلد",
            "dashboardMessageCountryExists" => "تم اضافة هذا البلد مسبقا",
            "dashboardMessageCountryNotExists" => "هذا البلد غير موجود",
            "dashboardMessageEnterCountryIcon" => "قم باختيار راية البلد",
            //// City
            "dashboardAddCity" => "اضافة مدينة",
            "dashboardEditCity" => "تعديل مدينة",
            "dashboardColumnCityLocationName" => "اسم المدينة",
            "dashboardMessageDeleteCity" => "تم حذف المدينة بنجاح",
            "dashboardNotFoundCity" => "لايوجد مدن حاليا",
            "dashboardMessageAddCity" => "تم اضافة المدينة بنجاح",
            "dashboardMessageEditCity" => "تم تعديل المدينة بنجاح",
            "dashboardMessageEnterCityName" => "ادخل اسم المدينة",
            "dashboardMessageCityExists" => "تم اضافة هذه المدينة مسبقا",
            //// Categories
            "dashboardCatMain" => "فئة رئيسية",
            "dashboardAddCategories" => "اضافة فئة",
            "dashboardEditCategories" => "تعديل فئة",
            "dashboardColumnCatName" => "اسم الفئة",
            "dashboardColumnCatDesc" => "وصف الفئة",
            "dashboardColumnCatIcon" => "ايقونة الفئة",
            "dashboardColumnCatNotIcon" => "لايوجد ايقونة",
            "dashboardColumnCatParent" => "نوع الفئة",
            "dashboardMessageDeleteCat" => "تم حذف الفئة بنجاح",
            "dashboardNotFoundCat" => "لايوجد فئات حاليا",
            "dashboardMessageAddCat" => "تم اضافة الفئة بنجاح",
            "dashboardMessageEditCat" => "تم تعديل الفئة بنجاح",
            "dashboardMessageEnterCatName" => "ادخل اسم الفئة",
            "dashboardMessageEnterCatDesc" => "ادخل وصف الفئة",
            "dashboardMessageEnterCatParent" => "ادخل نوع الفئة",
            "dashboardMessageCatExists" => "تم اضافة الفئة مسبقا",
            "dashboardMessageCatNotExists" => "هذه الفئة غير موجودة",
            "dashboardMessageEnterCatIcon" => "قم باختيار ايقونة الفئة",
            
            // reports
            "reportsClientTitle" => "ارسال تقرير",
            "reportsClientReportText" => "ماهو سبب الابلاغ عن هذا المنتج؟",
            "reportsClientMessageSuccess" => "تم ارسال الابلاغ, ستتم مراجعته من قبل المسؤولين",
            "reportsClientMessageError1" => "اكتب سبب كتابة التقرير",
            "reportsClientMessageError2" => "يجب ان لا يتجاوز عدد الاحرف 255 ولا يقل عن 3 احرف",
            "dashboardColumnReportText" => "سبب الابلاغ",
            "dashboardColumnReportTo" => "الاعلان الذي تم الابلاغ عنه",
            "dashboardMessageDeleteReport" => "تم حذف الابلاغ بنجاح",
            "dashboardNotFoundReports" => "لايوجد ابلاغات حاليا",
            
            // Not Found
            "TitleNotFound" => "عفواً لقد حدث خطأ ما!",
            "notfoundTitle" => "لم نستطيع ايجاد هذه الصفحة:",
            "listError1" => "تأكد من الرابط.",
            "listError2" => "ربما انتهت صلاحيته او حُذف.",
            "listError3" => "أو قد تم حذفه لانتهاك قوانين Syria Shop الخاصة بنشر الاعلانات.",
            "backToHome" => "العودة للصفحة الرئيسية",
            
            // Footer
            "footerTitle" => "قم بنشر اعلانك بشكل فوري ومجانا",
            "footerColumnLang" => "اللغات",
            "footerColumnFollow" => "تابعنا",
        );
        
        $en = array(
            // global
            "report" => "report",
            "unsave" => "Cancel saving",
            "AnUnexpectedErrorOccurred" => "An Unexpected Error Occurred",
            "dirTips" => "left",
            "btnAddAds" => "add Ads",
            "add" => "Add",
            "cancel" => "Cancel",
            "dashboard" => "dashboard",
            "learnMore" => "learn more",
            "allCountry" => "All Country",
            "allCity" => "All City",
            
            // Nav
            "signUp"    => "Sign Up",
            "signIn"    => "Sign In",
            "signInFace" => "LogIn with Facebook account",
            "more" => "More",
            "country" => "Country",
            "city" => "City",
            "profile" => "Profile",
            "chooseLang" => "Choose Lang",
            "titleGetAds1" => "Ads",
            "item1GetAds1" => "Selling ads",
            "item2GetAds1" => "Purchase Ads",
            "item3GetAds1" => "Rent ads",
            "item4GetAds1" => "all Ads",
            "categoriesNav" => "categories",
            "signOut" => "Sign Out",
            "inputSearch" => "search...",
            
            // Client Default
            "maxViews" => "Top Show",
            "newsAds" => "Latest ads",
            "notFoundAds" => "There are currently no ads",
            "readMore" => "Read More",
            "today" => "Today",
            "yesterday" => "yesterday",
            "twodays" => "Two days ago",
            "titleNotFoundAds" => "We apologize! There are no ads in this section",
            "textNotFoundAds" => "Try again later",
            "successAddFavorite" => "Added to favorites",
            "errorAddFavorite" => "Failed to add ads to favorites",
            "successRemoveFavorite" => "Remove from favorites",
            "errorRemoveFavorite" => "Failed to delete ad from favorites",
            "messageClientBlockUser" => "You have been banned from posting by the administrator",
            "titleContainerCountry" => "Choose the country whose ads you want to show",
            "titleContainerCity" => "Choose the city whose ads you want to show",
            "showLastAds" => "Show the latest ads",
            
            // SignIn & SignUp
            "email" => "Email",
            "password" => "Password",
            "remberMe" => "Rember Me",
            "forgetPassword" => "did you forget your password",
            "codeCheck" => "Enter the sum of the following two numbers",
            "dontHaveAccount" => "You do not have an account",
            "clickHere" => "Click Here",
            "username" => "User Name",
            "haveAccount" => "Do You Have An Account",
            "notEmptyEmail" => "Fill in the email field",
            "EmailIsExists" => "The email you entered already exists",
            "notEmptyUserName" => "Fill in the Name field",
            "countUserName" => "The number of characters must be greater than 4 characters and less than 40 characters",
            "checkValidEmail" => "Make sure the email is correct",
            "notEmptyPassword" => "Fill in the password field",
            "countPassword" => "Password must be greater than 5 characters and less than 40 characters",
            "passwordIncorrect" => "The password is incorrect",
            
            // Confirm Email
            "confirmTitle" => "verify your e-mail",
            "bodyMessageConfirm" => "You have created an account on the Syria Shop website, type the following verification code you were asked for in the verification box",
            "wellcomeConfirm" => "hello",
            "footerConfirm" => "Sincerely, <a href='https://www.facebook.com/qusayshartah'> Developer </a>",
            "EnterCode" => "Enter The Code",
            "sendCode" => "send",
            "noteConfirm" => "Enter the code that was sent to your email address",
            "notEmptyCode" => "Fill in the code field",
            "errorConfirmEmail" => "The code you entered is not valid",
            "messageSuccessResendCode" => "The code has been retransmitted",
            "messageErrorResendCode" => "Failed to send code",
            "resendCode" => "If you do not receive the code <a id='sendCode'> click here </a> to resend it again.",
            
            // reset Password
            "titleResetPassword" => "Password Reset",
            "noteAfterSendMail" => "A verification code has been sent to your email address. Check it in the Email or Spam section.",
            "checkEmail" => "Check your email",
            "EmailIsNotExists" => "The email you entered does not exist",
            "bodyMail" => "You have submitted a request to reset your password on Syria Shop. Type this code to be able to reset your password.",
            "save" => "save",
            "enterNewPasswprd" => "Enter your new password",
            
            // newAds Default
            "chooseCat" => "Choose a category",
            
            // newAds addAds
            "infoAds" => "Product Information",
            "catName" => "The ad will be saved in the section: ",
            "inputTitleAds" => "Ads Title",
            "inputDescAds"  => "Ads Description",
            "inputTypeAds"  => "Ads Type",
            "ads" => "Buy an Ads",
            "sellAproduct" => "Sell an Ads",
            "rentAproduct" => "rent an Ads",
            "phoneuser" => "The Phone",
            "countryNumber" => "Country key",
            "countryother" => "Other than that",
            "Examplephoneuser" => "Example: 956343074",
            "ExampleTags" => "Here you write the keywords that indicate your ad to appear in the search results",
            "whatsapp" => "Whatsapp",
            "priceAds" => "Product price in Syrian Pounds",
            "locationAds" => "The location of the product",
            "discountAds" => "Is the product negotiable",
            "tags" => "example: mobile+samsung+samsung s7",
            "expireAds" => "Ads end date",
            "sendAds" => "Send",
            "Adsformat" => "Product format",
            "negotiable" => "Negotiable",
            "locationads2" => "The presence of the product",
            "messageEmptyItemName" => "Fill in the Ad Title field",
            "messageGTItemName" => "The number of characters of the ad title must be greater than 3 characters and less than 50 characters",
            "messageEmptyItemDesc" => "Fill in the Ads Description field",
            "messageEmptyItemPrice" => "Fill in the Product Price field",
            "messageEmptyItemLocation" => "Select the location of the product",
            "messageEmptyItemType" => "Choose your ads type",
            "messageEmptyPhoneUser" => "Enter your phone number",
            "messageEmptyWhatsapp" => "Enter your WhatsApp number",
            "messageCountFile" => "The maximum number of files is 7",
            "messageAllowFile" => "Allowed files are png - jpg - jpeg - gif - mp4",
            "messageAllowFileImgOnly" => "Allowed files are png - jpg - jpeg - gif",
            "messageSizeFileImg" => "Image size should not exceed 10 MB",
            "messageSizeFileVideo" => "Video size should not exceed 40 MB",
            "messageLoadingTitle" => "please wait...",
            "messageLoadingNote" => "Now the product is added, please wait until the download finishes.",
            "titleMessageAlarm" => "Add new product",
            "messageAlarm1" => "A new item has been added to the section ",
            "messageAlarm2" => "Visit the site to view it",
            "messageAlarm3" => "Website link: http://syria-shop.com",
            "messageEmptyTags" => "Type at least one word in the Keywords field",
            "messageSuccessAddAds" => "Product successfully added",
            "messageDeleteAddAds" => "Product successfully deleted",
            "messageErrorAddAds" => "Something went wrong",
            
            // edit Ads
            "productAttachments" => "Product Attachments",
            "deleteImg" => "delete Attachment",
            "deletedAttachment" => "Attachment successfully deleted",
            "errorDeletedAttachments" => "Failed to delete attachment",
            "notFoundAttachments" => "The attachment does not exist or has been deleted",
            "messageCountFileEdit" => "The total number of attachments allowed is 7",
            "categorieName"  => "Categorie",
            
            // categories
            "enableAlarm" => "Alerts have been activated for this section",
            "disableAlarm" => "Alerts for this section have been deactivated",
            "enableDisabledAlarm" => "Activate / deactivate alerts",
            
            // Show Ads
            "showAdsCategorie" => "categorie",
            "showAdsCountry" => "Country",
            "showAdsLocation" => "Governorate",
            "showAdsPrice" => "Price",
            "showAdsRent" => "For Rent",
            "showAdsPhone" => "Phone",
            "showAdsWhatsapp" => "Whatsapp",
            "showAdsViews" => "Views",
            "showAdsDiscoint" => "Negotiable",
            "showAdsYes" => "Yes",
            "showAdsNo" => "No",
            "after" => "After",
            "1day" => "Today",
            "2day" => "2 Days",
            "3day" => "3 Days",
            "4day" => "4 Days",
            "5day" => "5 Days",
            "6day" => "6 Days",
            "7day" => "7 Days",
            "showAdsTags" => "Tags",
            "adsOthersTitle" => "Related Ads",
            "notFoundadsOthers" => "There are no ads related to this ads",
            
            // search
            "resultSearch" => "Search Results for ",
            
            // Profile
            "myAds" => "my ads",
            "myInfo" => "My information",
            "favorite" => "Favorite",
            "messageSuccessSaveData" => "Data saved",
            "messageLoadingTitleLogo" => "Saving ...",
            "messageLoadingNoteLogo" => "Updating profile picture, please wait.",
            "messageSuccessEditMyImg" => "Profile picture changed",
            "can'tChangeEmail" => "You cannot change your email",
            
            // Dashboard
            //// default
            "dashboardControlPanel" => "Control Panel",
            "dashboardClients" => "Clients",
            "dashboardAds" => "Ads",
            "dashboardCategories" => "Categories",
            "dashboardCountry" => "Country",
            "dashboardReports" => "Reports",
            "dashboardLastUsers" => "Last 5 Clients",
            "dashboardLastAds" => "Last 5 Ads",
            "dashboardNotFoundAds" => "There are currently no ads",
            "dashboardNotFoundUser" => "There are currently no Clients",
            "dashboardTitleStatistcItems" => "Ads stats",
            "dashboardTitleStatistcUsers" => "Users Stats",
            
            //// Users
            "dashboardTypeUser" => "User validity",
            "dashboardBlock" => "Ban / unblock",
            "dashboardControl" => "Control",
            "dashboardMessageDeleteUser" => "The user was deleted successfully",
            "dashboardMessageBlock" => "The user has been blocked successfully",
            "dashboardMessageUnBlock" => "The user was unblocked successfully",
            "dashboardMessagePermissions" => "Manager's permission has been successfully granted",
            "dashboardMessageUnPermissions" => "Manager's permission has been successfully revoked",
            //// Items
            "dashboardPublisher" => "Publisher",
            "dashboardCountry" => "Country",
            "dashboardCity" => "City",
            "dashboardViewItem" => "Watch The Ads",
            "dashboardDateAdded" => "Date added",
            
            //// Country
            "dashboardAddCountry" => "add country",
            "dashboardEditCountry" => "Edit Country",
            "dashboardColumnLocationName" => "country name",
            "dashboardColumnLocationIcon" => "Country banner",
            "dashboardColumnLocationCity" => "City",
            "dashboardMessageDeleteCountry" => "The country has been deleted successfully",
            "dashboardNotFoundCountry" => "There is currently no country",
            "dashboardMessageAddCountry" => "The country has been added successfully",
            "dashboardMessageEditCountry" => "The country has been Edit successfully",
            "dashboardMessageEnterCountryName" => "Enter the country name",
            "dashboardMessageCountryExists" => "This country has already been added",
            "dashboardMessageCountryNotExists" => "This country does not exist",
            "dashboardMessageEnterCountryIcon" => "Choose the country flag",
            //// City
            "dashboardAddCity" => "Add City",
            "dashboardEditCity" => "Edit City",
            "dashboardColumnCityLocationName" => "City Name",
            "dashboardMessageDeleteCity" => "The city has been deleted successfully",
            "dashboardNotFoundCity" => "There is currently no city",
            "dashboardMessageAddCity" => "The city has been added successfully",
            "dashboardMessageEditCity" => "The country has been Edit successfully",
            "dashboardMessageEnterCityName" => "Enter the city name",
            "dashboardMessageCityExists" => "This city has already been added",
            //// Categories
            "dashboardCatMain" => "Main section",
            "dashboardAddCategories" => "Add Categorie",
            "dashboardEditCategories" => "Edit Categorie",
            "dashboardColumnCatName" => "Categorie Name",
            "dashboardColumnCatDesc" => "Categorie Desscription",
            "dashboardColumnCatIcon" => "Categorie Icon",
            "dashboardColumnCatNotIcon" => "No icon",
            "dashboardColumnCatParent" => "Categorie Type",
            "dashboardMessageDeleteCat" => "The category was deleted successfully",
            "dashboardNotFoundCat" => "There are currently no categories",
            "dashboardMessageAddCat" => "The category was added successfully",
            "dashboardMessageEditCat" => "The category was modified successfully",
            "dashboardMessageEnterCatName" => "Enter a category name",
            "dashboardMessageEnterCatDesc" => "Enter a category description",
            "dashboardMessageEnterCatParent" => "Enter a category type",
            "dashboardMessageCatExists" => "The category was previously added",
            "dashboardMessageCatNotExists" => "This category does not exist",
            "dashboardMessageEnterCatIcon" => "Choose the category icon",
            
            // reports
            "reportsClientTitle" => "Submit a report",
            "reportsClientReportText" => "What is the reason for reporting this product?",
            "reportsClientMessageSuccess" => "The report has been sent, and it will be reviewed by officials",
            "reportsClientMessageError1" => "Write the reason for writing the report",
            "reportsClientMessageError2" => "The number of characters must not exceed 255 and not less than 3 characters",
            "dashboardColumnReportText" => "Reason for reporting",
            "dashboardColumnReportTo" => "The ads that was reported",
            "dashboardMessageDeleteReport" => "Reporting deleted successfully",
            "dashboardNotFoundReports" => "There are currently no reports",
            
            // Not Found
            "TitleNotFound" => "Sorry, something went wrong!",
            "notfoundTitle" => "We could not find this page:",
            "listError1" => "Check the link.",
            "listError2" => "It may have expired or been deleted.",
            "listError3" => "Or it has been deleted for violating Syria Shop advertising laws.",
            "backToHome" => "Return to the home page",
            // Footer
            "footerTitle" => "Post your ads instantly and for free",
            "footerColumnLang" => "Languages",
            "footerColumnFollow" => "Follow us",
        );
        
        switch ($lang) {
            case "ar": return $ar[$words]; break;
            case "en": return ucwords($en[$words]); break;
            default : return $ar[$words]; break;
        }
        
    }
    
}
